# S- SRP, PRINCIPIO DE RESPONSABILIDAD ÚNICO
# 0- OCP, PRINCIPIO DE ABIERTO/CERRADO
# L- LSP, PRINCIPIO DE SUSTITUCIÓN DE LISKOV
# I- ISP, PRINCIPIO DE SUSTITUCIÓN DE INTERFAZ
# D- DIP, PRINCIPIO DE INVERSIÓN DE DEPENDENCIAS

